import React, { useEffect, useRef } from "react";
import { widget } from "/charting_library-master/charting_library";
import "./index.css";
import { theme } from "antd";
import { baseURL } from "../../core/AxiosInstance";
// let paths = window.location.pathname.split("/");
function getLanguageFromURL() {
  const regex = new RegExp("[\\?&]lang=([^&#]*)");
  const results = regex.exec(window.location.search);

  return results === null
    ? null
    : decodeURIComponent(results[1].replace(/\+/g, " "));
}

export const TVChartContainer = ({ ticker }) => {
  const chartContainerRef = useRef();
  const defaultProps = {
    symbol: ticker,
    interval: "D",
    datafeedUrl: `${baseURL}/tradingview`,
    libraryPath: "/charting_library-master/charting_library/",
    chartsStorageUrl: "*",
    chartsStorageApiVersion: "1.1",
    // clientId: 'tradingview.com',
    userId: "public_user_id",
    fullscreen: false,
    autosize: true,
    studiesOverrides: {},
  };

  useEffect(() => {
    const widgetOptions = {
      ticker: defaultProps.symbol,
      symbol: defaultProps.symbol,
      datafeed: new window.Datafeeds.UDFCompatibleDatafeed(
        defaultProps.datafeedUrl
      ),
      interval: defaultProps.interval,
      container: chartContainerRef.current,
      library_path: defaultProps.libraryPath,
      locale: getLanguageFromURL() || "en",
      disabled_features: [
        "use_localstorage_for_settings",
        "header_symbol_search",
        "left_toolbar",
        "timeframes_toolbar",
      ],
      enabled_features: [
        "study_templates",
        "custom_resolutions",
        "show_spread_operators",
        "symbol_search_complete",
        "pay_attention_to_ticker_not_symbol",
        "disable_resolution_rebuild",
      ],
      // charts_storage_url: defaultProps.chartsStorageUrl,
      // charts_storage_api_version: defaultProps.chartsStorageApiVersion,
      // client_id: defaultProps.clientId,
      // user_id: defaultProps.userId,
      theme: "dark",
      overrides: {
        "paneProperties.background": "#151e1b",
        "paneProperties.backgroundType": "solid",
        "paneProperties.horzGridProperties.style": "2",
        "paneProperties.vertGridProperties.style": "2",
      },
      debug: true,
      fullscreen: defaultProps.fullscreen,
      autosize: defaultProps.autosize,
      studies_overrides: defaultProps.studiesOverrides,
      loading_screen: { backgroundColor: "#151e1b" },
      custom_themes: {
        light: {
          color1: [
            "#f5ebff",
            "#ead6fe",
            "#e0c2fe",
            "#d5adfe",
            "#cb99fd",
            "#c184fd",
            "#b670fd",
            "#ac5bfc",
            "#a147fc",
            "#9732fc",
            "#8209fb",
            "#7708e6",
            "#6c08d1",
            "#6207bc",
            "#5706a7",
            "#4c0592",
            "#41057e",
            "#360469",
            "#2b0354",
            "#21023f",
          ],
          color2: [
            "#f2edf7",
            "#e6dcef",
            "#d9cae7",
            "#ccb9df",
            "#bfa7d7",
            "#b396d0",
            "#a684c8",
            "#9972c0",
            "#8c61b8",
            "#804fb0",
            "#662ca0",
            "#5e2893",
            "#552585",
            "#4d2178",
            "#441d6b",
            "#3c1a5d",
            "#331650",
            "#2b1243",
            "#220f35",
            "#1a0b28",
          ],
          color3: [
            "#fff0f0",
            "#ffe1e1",
            "#ffd3d3",
            "#ffc4c4",
            "#ffb5b5",
            "#ffa6a6",
            "#ff9797",
            "#ff8888",
            "#ff7a7a",
            "#ed4d3f",
            "#ff4d4d",
            "#ea4747",
            "#d54040",
            "#bf3a3a",
            "#aa3333",
            "#952d2d",
            "#802727",
            "#6a2020",
            "#551a1a",
            "#401313",
          ],
          color4: [
            "#f2fdf8",
            "#e5faf0",
            "#d7f8e9",
            "#caf5e1",
            "#bdf3da",
            "#b0f1d2",
            "#a2eecb",
            "#95ecc3",
            "#88e9bc",
            "#7be7b4",
            "#60e2a5",
            "#58cf97",
            "#50bc8a",
            "#48aa7c",
            "#40976e",
            "#388460",
            "#307153",
            "#285e45",
            "#204b37",
            "#183929",
          ],
          color5: [
            "#fef5ea",
            "#fdecd5",
            "#fbe2bf",
            "#fad9aa",
            "#f9cf95",
            "#f8c680",
            "#f6bc6a",
            "#f5b255",
            "#f4a940",
            "#f39f2b",
            "#f08c00",
            "#dc8000",
            "#c87500",
            "#b46900",
            "#a05d00",
            "#8c5200",
            "#784600",
            "#643a00",
            "#502f00",
            "#3c2300",
          ],
          color6: [
            "#feeafe",
            "#fcd5fc",
            "#fbbffb",
            "#f9aaf9",
            "#f895f8",
            "#f780f7",
            "#f56af5",
            "#f455f4",
            "#f240f2",
            "#f12bf1",
            "#ee00ee",
            "#da00da",
            "#c600c6",
            "#b300b3",
            "#9f009f",
            "#8b008b",
            "#770077",
            "#630063",
            "#4f004f",
            "#3c003c",
          ],
          color7: [
            "#fefeea",
            "#fcfcd5",
            "#fbfbbf",
            "#f9f9aa",
            "#f8f895",
            "#f7f780",
            "#f5f56a",
            "#f4f455",
            "#f2f240",
            "#f1f12b",
            "#eeee00",
            "#dada00",
            "#c6c600",
            "#b3b300",
            "#9f9f00",
            "#8b8b00",
            "#777700",
            "#636300",
            "#4f4f00",
            "#3c3c00",
          ],
          white: "#f2e6ff",
          black: "#421b50",
        },
        dark: {
          color1: [
            "#fbefea",
            "#f7dfd5",
            "#f3cfc0",
            "#efbfaa",
            "#ebaf95",
            "#e89f80",
            "#e48f6b",
            "#e07f56",
            "#dc6f41",
            "#12b66f",
            "#d03f01",
            "#bf3a01",
            "#ad3501",
            "#9c2f01",
            "#8b2a01",
            "#792501",
            "#682001",
            "#571a00",
            "#451500",
            "#341000",
          ],
          color2: [
            "#f8eeee",
            "#f1dede",
            "#eacdcd",
            "#9db2ab",
            "#dbacac",
            "#9db2ab",
            "#cd8a8a",
            "#c67a7a",
            "#bf6969",
            "#79c2a2",
            "#a93737",
            "#9b3232",
            "#8d2e2e",
            "#3d534c",
            "#712525",
            "#0d1210",
            "#1d2b27",
            "#1d2b27",
            "#381212",
            "#2a0e0e",
          ],
          color3: [
            "#fff0f0",
            "#ffe1e1",
            "#ffd3d3",
            "#ffc4c4",
            "#ffb5b5",
            "#ffa6a6",
            "#ff9797",
            "#ff8888",
            "#ff7a7a",
            "#ed4d3f",
            "#ff4d4d",
            "#ea4747",
            "#d54040",
            "#bf3a3a",
            "#aa3333",
            "#952d2d",
            "#802727",
            "#6a2020",
            "#551a1a",
            "#401313",
          ],
          color4: [
            "#f2fffb",
            "#e6fff7",
            "#d9fff2",
            "#ccffee",
            "#bfffea",
            "#b3ffe6",
            "#a6ffe1",
            "#99ffdd",
            "#8cffd9",
            "#2ef67d",
            "#66ffcc",
            "#5eeabb",
            "#55d5aa",
            "#4dbf99",
            "#44aa88",
            "#3c9577",
            "#338066",
            "#2b6a55",
            "#225544",
            "#1a4033",
          ],
          color5: [
            "#fffff0",
            "#ffffe0",
            "#feffd1",
            "#feffc2",
            "#feffb2",
            "#feffa3",
            "#fdff94",
            "#fdff84",
            "#fdff75",
            "#fdff66",
            "#fcff47",
            "#e7ea41",
            "#d2d53b",
            "#bdbf35",
            "#a8aa2f",
            "#939529",
            "#7e8024",
            "#696a1e",
            "#545518",
            "#3f4012",
          ],
          color6: [
            "#fff1ff",
            "#ffe2ff",
            "#ffd4ff",
            "#ffc5ff",
            "#ffb7ff",
            "#ffa9ff",
            "#ff9aff",
            "#ff8cff",
            "#ff7dff",
            "#ff6fff",
            "#ff52ff",
            "#ea4bea",
            "#d544d5",
            "#bf3ebf",
            "#aa37aa",
            "#953095",
            "#802980",
            "#6a226a",
            "#551b55",
            "#401540",
          ],
          color7: [
            "#eff8ff",
            "#dff1ff",
            "#cfeaff",
            "#bee3ff",
            "#aedcff",
            "#9ed5ff",
            "#8eceff",
            "#7ec7ff",
            "#6ec0ff",
            "#5db9ff",
            "#3dabff",
            "#389dea",
            "#338fd5",
            "#2e80bf",
            "#2972aa",
            "#246495",
            "#1f5680",
            "#19476a",
            "#143955",
            "#0f2b40",
          ],
          white: "#ffffff",
          black: "#000000",
        },
      },
    };

    const tvWidget = new widget(widgetOptions);

    tvWidget.onChartReady(() => {
      tvWidget.headerReady().then(() => {
        const button = tvWidget.createButton();
        button.setAttribute("title", "Click to show a notification popup");
        button.classList.add("apply-common-tooltip");
        button.addEventListener("click", () =>
          tvWidget.showNoticeDialog({
            title: "Notification",
            body: "API works correctly",
            callback: () => {
              console.log("Noticed!");
            },
          })
        );

        button.innerHTML = "Check API";
      });
    });

    return () => {
      tvWidget.remove();
    };
  }, [ticker]);

  return <div ref={chartContainerRef} className={"TVChartContainer"} />;
};
