export const markets = [
  {
    id: 1,
    img: "/img/egax_logo.png",
    pair: "EGAX-EGOD",
    currentPrice: 1000,
    OpenPrice: 850,
    volume24h: 10000000,
  },
  {
    id: 2,
    img: "/img/egax_logo.png",
    pair: "EGC-EGOD",
    currentPrice: 1000,
    OpenPrice: 850,
    volume24h: 10000000,
  },
  {
    id: 3,
    img: "/img/egax_logo.png",
    pair: "BTC-EGOD",
    currentPrice: 1000,
    OpenPrice: 850,
    volume24h: 10000000,
  },
  {
    id: 4,
    img: "/img/egax_logo.png",
    pair: "PLT-EGOD",
    currentPrice: 1000,
    OpenPrice: 850,
    volume24h: 10000000,
  },
  {
    id: 5,
    img: "/img/egax_logo.png",
    pair: "EGAX-EGOD",
    currentPrice: 1000,
    OpenPrice: 850,
    volume24h: 10000000,
  },
  {
    id: 6,
    img: "/img/egax_logo.png",
    pair: "EGAX-EGOD",
    currentPrice: 1000,
    OpenPrice: 850,
    volume24h: 10000000,
  },
  {
    id: 7,
    img: "/img/egax_logo.png",
    pair: "EGAX-EGOD",
    currentPrice: 1000,
    OpenPrice: 850,
    volume24h: 10000000,
  },
  {
    id: 8,
    img: "/img/egax_logo.png",
    pair: "EGAX-EGOD",
    currentPrice: 1000,
    OpenPrice: 850,
    volume24h: 10000000,
  },
  {
    id: 9,
    img: "/img/egax_logo.png",
    pair: "EGAX-EGOD",
    currentPrice: 1000,
    OpenPrice: 850,
    volume24h: 10000000,
  },
  {
    id: 10,
    img: "/img/egax_logo.png",
    pair: "EGAX-EGOD",
    currentPrice: 1000,
    OpenPrice: 850,
    volume24h: 10000000,
  },
];
export const userAssets = [
  {
    id: 1,
    img: "/img/egax_logo.png",
    token: "EGAX",
    bal: 1000,
    lockedBal: 150,
    usdVal: 2800,
    tag: "erc20",
  },
  {
    id: 2,
    img: "/img/egc.png",
    token: "EGC",
    bal: 0,
    lockedBal: 0,
    usdVal: 0,
    tag: "erc20",
  },
  {
    id: 3,
    img: "/img/btc.png",
    token: "BTC",
    bal: 0,
    lockedBal: 0,
    usdVal: 0,
    tag: "erc20",
  },
  {
    id: 4,
    img: "/img/eth.png",
    token: "ETH",
    bal: 0,
    lockedBal: 0,
    usdVal: 0,
    tag: "erc20",
  },
  {
    id: 5,
    img: "/img/egax_logo.png",
    token: "EGAX",
    bal: 0,
    lockedBal: 0,
    usdVal: 0,
    tag: "erc20",
  },
  {
    id: 6,
    img: "/img/egc.png",
    token: "EGC",
    bal: 0,
    lockedBal: 0,
    usdVal: 0,
    tag: "erc20",
  },
  {
    id: 7,
    img: "/img/btc.png",
    token: "BTC",
    bal: 0,
    lockedBal: 0,
    usdVal: 0,
    tag: "erc20",
  },
  {
    id: 8,
    img: "/img/eth.png",
    token: "ETH",
    bal: 0,
    lockedBal: 0,
    usdVal: 0,
    tag: "erc20",
  },
  {
    id: 9,
    img: "/img/esta_logo.jpeg",
    token: "ESTA",
    bal: 0,
    lockedBal: 0,
    usdVal: 0,
    tag: "erc404",
  },
];
